#!/bin/bash

echo "=== AgentBench 平台使用指南 ==="
echo ""
echo "1. 环境检查:"
echo "   ✓ Node.js版本: $(node --version)"
echo "   ✓ npm版本: $(npm --version)"
echo ""
echo "2. 项目结构检查:"
echo "   ✓ 项目根目录: $(pwd)"
echo "   ✓ 主要文件存在:"
ls -la src/app/ | grep -E "(page\.tsx|layout\.tsx)"
echo ""
echo "3. 依赖检查:"
echo "   ✓ 核心依赖已安装:"
ls node_modules/ | grep -E "(next|react|typescript|tailwindcss|zustand|recharts|supabase)"
echo ""
echo "4. 下一步操作:"
echo "   1. 在 Supabase 创建项目"
echo "   2. 执行 supabase-schema.sql"
echo "   3. 配置 .env.local 文件"
echo "   4. 启动开发服务器: npm run dev"
echo "   5. 访问 http://localhost:3000"
echo ""
echo "=== 当前状态 ==="
echo "Phase 1 已完成 - 基础架构搭建完毕"
echo "可以开始 Phase 2 功能开发"